membersrvc0:
  extends:
    file: compose-defaults.yml
    service: membersrvc

vp0:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBatch
  environment:
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  external_links:
    - setup_membersrvc0_1:membersrvc0

vp1:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBatch
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
  external_links:
    - setup_membersrvc0_1:membersrvc0
    - setup_vp0_1:vp0

vp2:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBatch
  environment:
    - CORE_PEER_ID=vp2
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
  external_links:
    - setup_membersrvc0_1:membersrvc0
    - setup_vp0_1:vp0

vp3:
  extends:
    file: docker-compose-4-consensus-base.yml
    service: vpBatch
  environment:
    - CORE_PEER_ID=vp3
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
  external_links:
    - setup_membersrvc0_1:membersrvc0
    - setup_vp0_1:vp0
